export enum EnumEnviromentsProjectsReducer {
    SET_PROJECT_SELECTED = 'SET_PROJECT_SELECTED',
    SET_TECHNOLOGY_SELECTED = 'SET_TECHNOLOGY_SELECTED',
    SET_FILTERED_LIST_PROJECTS_BY_TECNOLOGY_SELECTED = 'SET_FILTERED_LIST_PROJECTS_BY_TECNOLOGY_SELECTED'
}